name: Build and publish Renode Docker image to GHCR

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/renode-${{ github.event.repository.name }}
  RENODE_VERSION: "1.16.0"

jobs:
  build-and-push-arch:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: linux/amd64
            arch_tag: amd64
            renode_pkg: linux-portable-dotnet
          - platform: linux/arm64
            arch_tag: arm64
            renode_pkg: linux-arm64-portable-dotnet
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./defmt_cs/
          file: ./defmt_cs/Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            RENODE_VERSION=${{ env.RENODE_VERSION }}
            RENODE_PKG=${{ matrix.renode_pkg }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest-${{ matrix.arch_tag }}
#          labels: |
#            ${{ steps.meta.outputs.labels.created }}
#            ${{ steps.meta.outputs.labels.description }}
#            ${{ steps.meta.outputs.labels.licenses }}
#            ${{ steps.meta.outputs.labels.revision }}
#            ${{ steps.meta.outputs.labels.source }}

#labels:
#  - org.opencontainers.image.created=2026-02-02T19:14:16.344Z
#  - org.opencontainers.image.description=
#  - org.opencontainers.image.licenses=
#  - org.opencontainers.image.revision=806e75717400e16acb6d356254a9082734d70426
#  - org.opencontainers.image.source=https://github.com/blumenplace/skju
#  - org.opencontainers.image.title=skju
#  - org.opencontainers.image.url=https://github.com/blumenplace/skju
#  - org.opencontainers.image.version=main


  publish-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-arch
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest (:latest)
        run: |
          docker buildx imagetools create \
            -t "${IMAGE_NAME}:latest" \
            "${IMAGE_NAME}:latest-amd64" \
            "${IMAGE_NAME}:latest-arm64"
